language: scala
sudo: false

jdk:
  - oraclejdk8

scala:
  - 2.11.7

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

script:
  - sbt ++$TRAVIS_SCALA_VERSION travis
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/860acd787c2ef2f7ff06
    on_success: change
    on_failure: always
    on_start: never

before_install:
  - pip install --user codecov

after_success:
  - codecov
